version: '3.8'

services:
  schedule:
    build:
      context: ./schedule_app
      dockerfile: Dockerfile
    container_name: git_schedule_1
    volumes:
      - /home/ubuntu/start-container.sh:/host_scripts/start-container.sh:ro  # ✅ Mount from host with read-only
    networks:
      git_default:
        ipv4_address: 10.89.0.2

  main:
    build:
      context: ./main_app
      dockerfile: Dockerfile
    container_name: git_main_1
    networks:
      git_default:
        ipv4_address: 10.89.0.3
    restart: "no"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: git_nginx_1
    ports:
      - "8080:80"
    networks:
      git_default:
        ipv4_address: 10.89.0.4
    depends_on:
      - schedule

networks:
  git_default:
    driver: bridge
    ipam:
      config:
        - subnet: 10.89.0.0/24
